/**
 * Elements of the periodic table
 */
#[derive(Debug)]
#[allow(dead_code)]
pub struct Element {
    atomic_number: u8,
    symbol: &'static str,
    name: &'static str,
    atomic_mass: f32,
    cpk_hex_color: Option<&'static str>,
    electron_configuration: &'static str,
    electronegativity: Option<f32>,
    atomic_radius: Option<f32>,
    ionization_energy: Option<f32>,
    electron_affinity: Option<f32>,
    oxidation_states: &'static [i8],
    standard_state: &'static str,
    melting_point: Option<f32>,
    boiling_point: Option<f32>,
    density: Option<f32>,
    group_block: &'static str,
    year_discovered: Option<u16>,
}

/**
 * List of elements of the periodic table
 */
pub const ELEMENTS: &'static [Element] = &[
    Element {
        atomic_number: 1,
        symbol: "H",
        name: "Hydrogen",
        atomic_mass: 1.0080,
        cpk_hex_color: Some("FFFFFF"),
        electron_configuration: "1s1",
        electronegativity: Some(2.2),
        atomic_radius: Some(120.0),
        ionization_energy: Some(13.598),
        electron_affinity: Some(0.754),
        oxidation_states: &[1, -1],
        standard_state: "Gas",
        melting_point: Some(13.81),
        boiling_point: Some(20.28),
        density: Some(0.00008988),
        group_block: "Nonmetal",
        year_discovered: Some(1766),
    },
    Element {
        atomic_number: 2,
        symbol: "He",
        name: "Helium",
        atomic_mass: 4.00260,
        cpk_hex_color: Some("D9FFFF"),
        electron_configuration: "1s2",
        electronegativity: None,
        atomic_radius: Some(140.0),
        ionization_energy: Some(24.587),
        electron_affinity: None,
        oxidation_states: &[0],
        standard_state: "Gas",
        melting_point: Some(0.95),
        boiling_point: Some(4.22),
        density: Some(0.0001785),
        group_block: "Noble gas",
        year_discovered: Some(1868),
    },
    Element {
        atomic_number: 3,
        symbol: "Li",
        name: "Lithium",
        atomic_mass: 7.0,
        cpk_hex_color: Some("CC80FF"),
        electron_configuration: "[He]2s1",
        electronegativity: Some(0.98),
        atomic_radius: Some(182.0),
        ionization_energy: Some(5.392),
        electron_affinity: Some(0.618),
        oxidation_states: &[1],
        standard_state: "Solid",
        melting_point: Some(453.65),
        boiling_point: Some(1615.0),
        density: Some(0.534),
        group_block: "Alkali metal",
        year_discovered: Some(1817),
    },
    Element {
        atomic_number: 4,
        symbol: "Be",
        name: "Beryllium",
        atomic_mass: 9.012183,
        cpk_hex_color: Some("C2FF00"),
        electron_configuration: "[He]2s2",
        electronegativity: Some(1.57),
        atomic_radius: Some(153.0),
        ionization_energy: Some(9.323),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(1560.0),
        boiling_point: Some(2744.0),
        density: Some(1.85),
        group_block: "Alkaline earth metal",
        year_discovered: Some(1798),
    },
    Element {
        atomic_number: 5,
        symbol: "B",
        name: "Boron",
        atomic_mass: 10.81,
        cpk_hex_color: Some("FFB5B5"),
        electron_configuration: "[He]2s2 2p1",
        electronegativity: Some(2.04),
        atomic_radius: Some(192.0),
        ionization_energy: Some(8.298),
        electron_affinity: Some(0.277),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(2348.0),
        boiling_point: Some(4273.0),
        density: Some(2.37),
        group_block: "Metalloid",
        year_discovered: Some(1808),
    },
    Element {
        atomic_number: 6,
        symbol: "C",
        name: "Carbon",
        atomic_mass: 12.011,
        cpk_hex_color: Some("909090"),
        electron_configuration: "[He]2s2 2p2",
        electronegativity: Some(2.55),
        atomic_radius: Some(170.0),
        ionization_energy: Some(11.260),
        electron_affinity: Some(1.263),
        oxidation_states: &[4, 2, -4],
        standard_state: "Solid",
        melting_point: Some(3823.0),
        boiling_point: Some(4098.0),
        density: Some(2.2670),
        group_block: "Nonmetal",
        year_discovered: None,
    },
    Element {
        atomic_number: 7,
        symbol: "N",
        name: "Nitrogen",
        atomic_mass: 14.007,
        cpk_hex_color: Some("3050F8"),
        electron_configuration: "[He] 2s2 2p3",
        electronegativity: Some(3.04),
        atomic_radius: Some(155.0),
        ionization_energy: Some(14.534),
        electron_affinity: None,
        oxidation_states: &[5, 4, 3, 2, 1, -1, -2, -3],
        standard_state: "Gas",
        melting_point: Some(63.15),
        boiling_point: Some(77.36),
        density: Some(0.0012506),
        group_block: "Nonmetal",
        year_discovered: Some(1772),
    },
    Element {
        atomic_number: 8,
        symbol: "O",
        name: "Oxygen",
        atomic_mass: 15.999,
        cpk_hex_color: Some("FF0D0D"),
        electron_configuration: "[He]2s2 2p4",
        electronegativity: Some(3.44),
        atomic_radius: Some(152.0),
        ionization_energy: Some(13.618),
        electron_affinity: Some(1.461),
        oxidation_states: &[-2],
        standard_state: "Gas",
        melting_point: Some(54.36),
        boiling_point: Some(90.2),
        density: Some(0.001429),
        group_block: "Nonmetal",
        year_discovered: Some(1774),
    },
    Element {
        atomic_number: 9,
        symbol: "F",
        name: "Fluorine",
        atomic_mass: 18.99840316,
        cpk_hex_color: Some("90E050"),
        electron_configuration: "[He]2s2 2p5",
        electronegativity: Some(3.98),
        atomic_radius: Some(135.0),
        ionization_energy: Some(17.423),
        electron_affinity: Some(3.339),
        oxidation_states: &[-1],
        standard_state: "Gas",
        melting_point: Some(53.53),
        boiling_point: Some(85.03),
        density: Some(0.001696),
        group_block: "Halogen",
        year_discovered: Some(1670),
    },
    Element {
        atomic_number: 10,
        symbol: "Ne",
        name: "Neon",
        atomic_mass: 20.180,
        cpk_hex_color: Some("B3E3F5"),
        electron_configuration: "[He]2s2 2p6",
        electronegativity: None,
        atomic_radius: Some(154.0),
        ionization_energy: Some(21.565),
        electron_affinity: None,
        oxidation_states: &[0],
        standard_state: "Gas",
        melting_point: Some(24.56),
        boiling_point: Some(27.07),
        density: Some(0.0008999),
        group_block: "Noble gas",
        year_discovered: Some(1898),
    },
    Element {
        atomic_number: 11,
        symbol: "Na",
        name: "Sodium",
        atomic_mass: 22.9897693,
        cpk_hex_color: Some("AB5CF2"),
        electron_configuration: "[Ne]3s1",
        electronegativity: Some(0.93),
        atomic_radius: Some(227.0),
        ionization_energy: Some(5.139),
        electron_affinity: Some(0.548),
        oxidation_states: &[1],
        standard_state: "Solid",
        melting_point: Some(370.95),
        boiling_point: Some(1156.0),
        density: Some(0.97),
        group_block: "Alkali metal",
        year_discovered: Some(1807),
    },
    Element {
        atomic_number: 12,
        symbol: "Mg",
        name: "Magnesium",
        atomic_mass: 24.305,
        cpk_hex_color: Some("8AFF00"),
        electron_configuration: "[Ne]3s2",
        electronegativity: Some(1.31),
        atomic_radius: Some(173.0),
        ionization_energy: Some(7.646),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(923.0),
        boiling_point: Some(1363.0),
        density: Some(1.74),
        group_block: "Alkaline earth metal",
        year_discovered: Some(1808),
    },
    Element {
        atomic_number: 13,
        symbol: "Al",
        name: "Aluminum",
        atomic_mass: 26.981538,
        cpk_hex_color: Some("BFA6A6"),
        electron_configuration: "[Ne]3s2 3p1",
        electronegativity: Some(1.61),
        atomic_radius: Some(184.0),
        ionization_energy: Some(5.986),
        electron_affinity: Some(0.441),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(933.437),
        boiling_point: Some(2792.0),
        density: Some(2.70),
        group_block: "Post-transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 14,
        symbol: "Si",
        name: "Silicon",
        atomic_mass: 28.085,
        cpk_hex_color: Some("F0C8A0"),
        electron_configuration: "[Ne]3s2 3p2",
        electronegativity: Some(1.9),
        atomic_radius: Some(210.0),
        ionization_energy: Some(8.152),
        electron_affinity: Some(1.385),
        oxidation_states: &[4, 2, -4],
        standard_state: "Solid",
        melting_point: Some(1687.0),
        boiling_point: Some(3538.0),
        density: Some(2.3296),
        group_block: "Metalloid",
        year_discovered: Some(1854),
    },
    Element {
        atomic_number: 15,
        symbol: "P",
        name: "Phosphorus",
        atomic_mass: 30.97376200,
        cpk_hex_color: Some("FF8000"),
        electron_configuration: "[Ne]3s2 3p3",
        electronegativity: Some(2.19),
        atomic_radius: Some(180.0),
        ionization_energy: Some(10.487),
        electron_affinity: Some(0.746),
        oxidation_states: &[5, 3, -3],
        standard_state: "Solid",
        melting_point: Some(317.3),
        boiling_point: Some(553.65),
        density: Some(1.82),
        group_block: "Nonmetal",
        year_discovered: Some(1669),
    },
    Element {
        atomic_number: 16,
        symbol: "S",
        name: "Sulfur",
        atomic_mass: 32.07,
        cpk_hex_color: Some("FFFF30"),
        electron_configuration: "[Ne]3s2 3p4",
        electronegativity: Some(2.58),
        atomic_radius: Some(180.0),
        ionization_energy: Some(10.360),
        electron_affinity: Some(2.077),
        oxidation_states: &[6, 4, -2],
        standard_state: "Solid",
        melting_point: Some(388.36),
        boiling_point: Some(717.75),
        density: Some(2.067),
        group_block: "Nonmetal",
        year_discovered: None,
    },
    Element {
        atomic_number: 17,
        symbol: "Cl",
        name: "Chlorine",
        atomic_mass: 35.45,
        cpk_hex_color: Some("1FF01F"),
        electron_configuration: "[Ne]3s2 3p5",
        electronegativity: Some(3.16),
        atomic_radius: Some(175.0),
        ionization_energy: Some(12.968),
        electron_affinity: Some(3.617),
        oxidation_states: &[7, 5, 1, -1],
        standard_state: "Gas",
        melting_point: Some(171.65),
        boiling_point: Some(239.11),
        density: Some(0.003214),
        group_block: "Halogen",
        year_discovered: Some(1774),
    },
    Element {
        atomic_number: 18,
        symbol: "Ar",
        name: "Argon",
        atomic_mass: 39.9,
        cpk_hex_color: Some("80D1E3"),
        electron_configuration: "[Ne]3s2 3p6",
        electronegativity: None,
        atomic_radius: Some(188.0),
        ionization_energy: Some(15.760),
        electron_affinity: None,
        oxidation_states: &[0],
        standard_state: "Gas",
        melting_point: Some(83.8),
        boiling_point: Some(87.3),
        density: Some(0.0017837),
        group_block: "Noble gas",
        year_discovered: Some(1894),
    },
    Element {
        atomic_number: 19,
        symbol: "K",
        name: "Potassium",
        atomic_mass: 39.0983,
        cpk_hex_color: Some("8F40D4"),
        electron_configuration: "[Ar]4s1",
        electronegativity: Some(0.82),
        atomic_radius: Some(275.0),
        ionization_energy: Some(4.341),
        electron_affinity: Some(0.501),
        oxidation_states: &[1],
        standard_state: "Solid",
        melting_point: Some(336.53),
        boiling_point: Some(1032.0),
        density: Some(0.89),
        group_block: "Alkali metal",
        year_discovered: Some(1807),
    },
    Element {
        atomic_number: 20,
        symbol: "Ca",
        name: "Calcium",
        atomic_mass: 40.08,
        cpk_hex_color: Some("3DFF00"),
        electron_configuration: "[Ar]4s2",
        electronegativity: Some(1.0),
        atomic_radius: Some(231.0),
        ionization_energy: Some(6.113),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(1115.0),
        boiling_point: Some(1757.0),
        density: Some(1.54),
        group_block: "Alkaline earth metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 21,
        symbol: "Sc",
        name: "Scandium",
        atomic_mass: 44.95591,
        cpk_hex_color: Some("E6E6E6"),
        electron_configuration: "[Ar]4s2 3d1",
        electronegativity: Some(1.36),
        atomic_radius: Some(211.0),
        ionization_energy: Some(6.561),
        electron_affinity: Some(0.188),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1814.0),
        boiling_point: Some(3109.0),
        density: Some(2.99),
        group_block: "Transition metal",
        year_discovered: Some(1879),
    },
    Element {
        atomic_number: 22,
        symbol: "Ti",
        name: "Titanium",
        atomic_mass: 47.867,
        cpk_hex_color: Some("BFC2C7"),
        electron_configuration: "[Ar]4s2 3d2",
        electronegativity: Some(1.54),
        atomic_radius: Some(187.0),
        ionization_energy: Some(6.828),
        electron_affinity: Some(0.079),
        oxidation_states: &[4, 3, 2],
        standard_state: "Solid",
        melting_point: Some(1941.0),
        boiling_point: Some(3560.0),
        density: Some(4.5),
        group_block: "Transition metal",
        year_discovered: Some(1791),
    },
    Element {
        atomic_number: 23,
        symbol: "V",
        name: "Vanadium",
        atomic_mass: 50.9415,
        cpk_hex_color: Some("A6A6AB"),
        electron_configuration: "[Ar]4s2 3d3",
        electronegativity: Some(1.63),
        atomic_radius: Some(179.0),
        ionization_energy: Some(6.746),
        electron_affinity: Some(0.525),
        oxidation_states: &[5, 4, 3, 2],
        standard_state: "Solid",
        melting_point: Some(2183.0),
        boiling_point: Some(3680.0),
        density: Some(6.0),
        group_block: "Transition metal",
        year_discovered: Some(1801),
    },
    Element {
        atomic_number: 24,
        symbol: "Cr",
        name: "Chromium",
        atomic_mass: 51.996,
        cpk_hex_color: Some("8A99C7"),
        electron_configuration: "[Ar]3d5 4s1",
        electronegativity: Some(1.66),
        atomic_radius: Some(189.0),
        ionization_energy: Some(6.767),
        electron_affinity: Some(0.666),
        oxidation_states: &[6, 3, 2],
        standard_state: "Solid",
        melting_point: Some(2180.0),
        boiling_point: Some(2944.0),
        density: Some(7.15),
        group_block: "Transition metal",
        year_discovered: Some(1797),
    },
    Element {
        atomic_number: 25,
        symbol: "Mn",
        name: "Manganese",
        atomic_mass: 54.93804,
        cpk_hex_color: Some("9C7AC7"),
        electron_configuration: "[Ar]4s2 3d5",
        electronegativity: Some(1.55),
        atomic_radius: Some(197.0),
        ionization_energy: Some(7.434),
        electron_affinity: None,
        oxidation_states: &[7, 4, 3, 2],
        standard_state: "Solid",
        melting_point: Some(1519.0),
        boiling_point: Some(2334.0),
        density: Some(7.3),
        group_block: "Transition metal",
        year_discovered: Some(1774),
    },
    Element {
        atomic_number: 26,
        symbol: "Fe",
        name: "Iron",
        atomic_mass: 55.84,
        cpk_hex_color: Some("E06633"),
        electron_configuration: "[Ar]4s2 3d6",
        electronegativity: Some(1.83),
        atomic_radius: Some(194.0),
        ionization_energy: Some(7.902),
        electron_affinity: Some(0.163),
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1811.0),
        boiling_point: Some(3134.0),
        density: Some(7.874),
        group_block: "Transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 27,
        symbol: "Co",
        name: "Cobalt",
        atomic_mass: 58.93319,
        cpk_hex_color: Some("F090A0"),
        electron_configuration: "[Ar]4s2 3d7",
        electronegativity: Some(1.88),
        atomic_radius: Some(192.0),
        ionization_energy: Some(7.881),
        electron_affinity: Some(0.661),
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1768.0),
        boiling_point: Some(3200.0),
        density: Some(8.86),
        group_block: "Transition metal",
        year_discovered: Some(1735),
    },
    Element {
        atomic_number: 28,
        symbol: "Ni",
        name: "Nickel",
        atomic_mass: 58.693,
        cpk_hex_color: Some("50D050"),
        electron_configuration: "[Ar]4s2 3d8",
        electronegativity: Some(1.91),
        atomic_radius: Some(163.0),
        ionization_energy: Some(7.640),
        electron_affinity: Some(1.156),
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1728.0),
        boiling_point: Some(3186.0),
        density: Some(8.912),
        group_block: "Transition metal",
        year_discovered: Some(1751),
    },
    Element {
        atomic_number: 29,
        symbol: "Cu",
        name: "Copper",
        atomic_mass: 63.55,
        cpk_hex_color: Some("C88033"),
        electron_configuration: "[Ar]4s1 3d10",
        electronegativity: Some(1.9),
        atomic_radius: Some(140.0),
        ionization_energy: Some(7.726),
        electron_affinity: Some(1.228),
        oxidation_states: &[2, 1],
        standard_state: "Solid",
        melting_point: Some(1357.77),
        boiling_point: Some(2835.0),
        density: Some(8.933),
        group_block: "Transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 30,
        symbol: "Zn",
        name: "Zinc",
        atomic_mass: 65.4,
        cpk_hex_color: Some("7D80B0"),
        electron_configuration: "[Ar]4s2 3d10",
        electronegativity: Some(1.65),
        atomic_radius: Some(139.0),
        ionization_energy: Some(9.394),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(692.68),
        boiling_point: Some(1180.0),
        density: Some(7.134),
        group_block: "Transition metal",
        year_discovered: Some(1746),
    },
    Element {
        atomic_number: 31,
        symbol: "Ga",
        name: "Gallium",
        atomic_mass: 69.723,
        cpk_hex_color: Some("C28F8F"),
        electron_configuration: "[Ar]4s2 3d10 4p1",
        electronegativity: Some(1.81),
        atomic_radius: Some(187.0),
        ionization_energy: Some(5.999),
        electron_affinity: Some(0.3),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(302.91),
        boiling_point: Some(2477.0),
        density: Some(5.91),
        group_block: "Post-transition metal",
        year_discovered: Some(1875),
    },
    Element {
        atomic_number: 32,
        symbol: "Ge",
        name: "Germanium",
        atomic_mass: 72.63,
        cpk_hex_color: Some("668F8F"),
        electron_configuration: "[Ar]4s2 3d10 4p2",
        electronegativity: Some(2.01),
        atomic_radius: Some(211.0),
        ionization_energy: Some(7.900),
        electron_affinity: Some(1.35),
        oxidation_states: &[4, 2],
        standard_state: "Solid",
        melting_point: Some(1211.4),
        boiling_point: Some(3106.0),
        density: Some(5.323),
        group_block: "Metalloid",
        year_discovered: Some(1886),
    },
    Element {
        atomic_number: 33,
        symbol: "As",
        name: "Arsenic",
        atomic_mass: 74.92159,
        cpk_hex_color: Some("BD80E3"),
        electron_configuration: "[Ar]4s2 3d10 4p3",
        electronegativity: Some(2.18),
        atomic_radius: Some(185.0),
        ionization_energy: Some(9.815),
        electron_affinity: Some(0.81),
        oxidation_states: &[5, 3, -3],
        standard_state: "Solid",
        melting_point: Some(1090.0),
        boiling_point: Some(887.0),
        density: Some(5.776),
        group_block: "Metalloid",
        year_discovered: None,
    },
    Element {
        atomic_number: 34,
        symbol: "Se",
        name: "Selenium",
        atomic_mass: 78.97,
        cpk_hex_color: Some("FFA100"),
        electron_configuration: "[Ar]4s2 3d10 4p4",
        electronegativity: Some(2.55),
        atomic_radius: Some(190.0),
        ionization_energy: Some(9.752),
        electron_affinity: Some(2.021),
        oxidation_states: &[6, 4, -2],
        standard_state: "Solid",
        melting_point: Some(493.65),
        boiling_point: Some(958.0),
        density: Some(4.809),
        group_block: "Nonmetal",
        year_discovered: Some(1817),
    },
    Element {
        atomic_number: 35,
        symbol: "Br",
        name: "Bromine",
        atomic_mass: 79.90,
        cpk_hex_color: Some("A62929"),
        electron_configuration: "[Ar]4s2 3d10 4p5",
        electronegativity: Some(2.96),
        atomic_radius: Some(183.0),
        ionization_energy: Some(11.814),
        electron_affinity: Some(3.365),
        oxidation_states: &[5, 1, -1],
        standard_state: "Liquid",
        melting_point: Some(265.95),
        boiling_point: Some(331.95),
        density: Some(3.11),
        group_block: "Halogen",
        year_discovered: Some(1826),
    },
    Element {
        atomic_number: 36,
        symbol: "Kr",
        name: "Krypton",
        atomic_mass: 83.80,
        cpk_hex_color: Some("5CB8D1"),
        electron_configuration: "[Ar]4s2 3d10 4p6",
        electronegativity: Some(3.0),
        atomic_radius: Some(202.0),
        ionization_energy: Some(14.0),
        electron_affinity: None,
        oxidation_states: &[0],
        standard_state: "Gas",
        melting_point: Some(115.79),
        boiling_point: Some(119.93),
        density: Some(0.003733),
        group_block: "Noble gas",
        year_discovered: Some(1898),
    },
    Element {
        atomic_number: 37,
        symbol: "Rb",
        name: "Rubidium",
        atomic_mass: 85.468,
        cpk_hex_color: Some("702EB0"),
        electron_configuration: "[Kr]5s1",
        electronegativity: Some(0.82),
        atomic_radius: Some(303.0),
        ionization_energy: Some(4.177),
        electron_affinity: Some(0.468),
        oxidation_states: &[1],
        standard_state: "Solid",
        melting_point: Some(312.46),
        boiling_point: Some(961.0),
        density: Some(1.53),
        group_block: "Alkali metal",
        year_discovered: Some(1861),
    },
    Element {
        atomic_number: 38,
        symbol: "Sr",
        name: "Strontium",
        atomic_mass: 87.62,
        cpk_hex_color: Some("00FF00"),
        electron_configuration: "[Kr]5s2",
        electronegativity: Some(0.95),
        atomic_radius: Some(249.0),
        ionization_energy: Some(5.695),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(1050.0),
        boiling_point: Some(1655.0),
        density: Some(2.64),
        group_block: "Alkaline earth metal",
        year_discovered: Some(1790),
    },
    Element {
        atomic_number: 39,
        symbol: "Y",
        name: "Yttrium",
        atomic_mass: 88.90584,
        cpk_hex_color: Some("94FFFF"),
        electron_configuration: "[Kr]5s2 4d1",
        electronegativity: Some(1.22),
        atomic_radius: Some(219.0),
        ionization_energy: Some(6.217),
        electron_affinity: Some(0.307),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1795.0),
        boiling_point: Some(3618.0),
        density: Some(4.47),
        group_block: "Transition metal",
        year_discovered: Some(1794),
    },
    Element {
        atomic_number: 40,
        symbol: "Zr",
        name: "Zirconium",
        atomic_mass: 91.22,
        cpk_hex_color: Some("94E0E0"),
        electron_configuration: "[Kr]5s2 4d2",
        electronegativity: Some(1.33),
        atomic_radius: Some(186.0),
        ionization_energy: Some(6.634),
        electron_affinity: Some(0.426),
        oxidation_states: &[4],
        standard_state: "Solid",
        melting_point: Some(2128.0),
        boiling_point: Some(4682.0),
        density: Some(6.52),
        group_block: "Transition metal",
        year_discovered: Some(1789),
    },
    Element {
        atomic_number: 41,
        symbol: "Nb",
        name: "Niobium",
        atomic_mass: 92.90637,
        cpk_hex_color: Some("73C2C9"),
        electron_configuration: "[Kr]5s1 4d4",
        electronegativity: Some(1.6),
        atomic_radius: Some(207.0),
        ionization_energy: Some(6.759),
        electron_affinity: Some(0.893),
        oxidation_states: &[5, 3],
        standard_state: "Solid",
        melting_point: Some(2750.0),
        boiling_point: Some(5017.0),
        density: Some(8.57),
        group_block: "Transition metal",
        year_discovered: Some(1801),
    },
    Element {
        atomic_number: 42,
        symbol: "Mo",
        name: "Molybdenum",
        atomic_mass: 95.95,
        cpk_hex_color: Some("54B5B5"),
        electron_configuration: "[Kr]5s1 4d5",
        electronegativity: Some(2.16),
        atomic_radius: Some(209.0),
        ionization_energy: Some(7.092),
        electron_affinity: Some(0.746),
        oxidation_states: &[6],
        standard_state: "Solid",
        melting_point: Some(2896.0),
        boiling_point: Some(4912.0),
        density: Some(10.2),
        group_block: "Transition metal",
        year_discovered: Some(1778),
    },
    Element {
        atomic_number: 43,
        symbol: "Tc",
        name: "Technetium",
        atomic_mass: 96.90636,
        cpk_hex_color: Some("3B9E9E"),
        electron_configuration: "[Kr]5s2 4d5",
        electronegativity: Some(1.9),
        atomic_radius: Some(209.0),
        ionization_energy: Some(7.28),
        electron_affinity: Some(0.55),
        oxidation_states: &[7, 6, 4],
        standard_state: "Solid",
        melting_point: Some(2430.0),
        boiling_point: Some(4538.0),
        density: Some(11.0),
        group_block: "Transition metal",
        year_discovered: Some(1937),
    },
    Element {
        atomic_number: 44,
        symbol: "Ru",
        name: "Ruthenium",
        atomic_mass: 101.1,
        cpk_hex_color: Some("248F8F"),
        electron_configuration: "[Kr]5s1 4d7",
        electronegativity: Some(2.2),
        atomic_radius: Some(207.0),
        ionization_energy: Some(7.361),
        electron_affinity: Some(1.05),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(2607.0),
        boiling_point: Some(4423.0),
        density: Some(12.1),
        group_block: "Transition metal",
        year_discovered: Some(1827),
    },
    Element {
        atomic_number: 45,
        symbol: "Rh",
        name: "Rhodium",
        atomic_mass: 102.9055,
        cpk_hex_color: Some("0A7D8C"),
        electron_configuration: "[Kr]5s1 4d8",
        electronegativity: Some(2.28),
        atomic_radius: Some(195.0),
        ionization_energy: Some(7.459),
        electron_affinity: Some(1.137),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(2237.0),
        boiling_point: Some(3968.0),
        density: Some(12.4),
        group_block: "Transition metal",
        year_discovered: Some(1803),
    },
    Element {
        atomic_number: 46,
        symbol: "Pd",
        name: "Palladium",
        atomic_mass: 106.42,
        cpk_hex_color: Some("6985"),
        electron_configuration: "[Kr]4d10",
        electronegativity: Some(2.2),
        atomic_radius: Some(202.0),
        ionization_energy: Some(8.337),
        electron_affinity: Some(0.557),
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1828.05),
        boiling_point: Some(3236.0),
        density: Some(12.0),
        group_block: "Transition metal",
        year_discovered: Some(1803),
    },
    Element {
        atomic_number: 47,
        symbol: "Ag",
        name: "Silver",
        atomic_mass: 107.868,
        cpk_hex_color: Some("C0C0C0"),
        electron_configuration: "[Kr]5s1 4d10",
        electronegativity: Some(1.93),
        atomic_radius: Some(172.0),
        ionization_energy: Some(7.576),
        electron_affinity: Some(1.302),
        oxidation_states: &[1],
        standard_state: "Solid",
        melting_point: Some(1234.93),
        boiling_point: Some(2435.0),
        density: Some(10.501),
        group_block: "Transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 48,
        symbol: "Cd",
        name: "Cadmium",
        atomic_mass: 112.41,
        cpk_hex_color: Some("FFD98F"),
        electron_configuration: "[Kr]5s2 4d10",
        electronegativity: Some(1.69),
        atomic_radius: Some(158.0),
        ionization_energy: Some(8.994),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(594.22),
        boiling_point: Some(1040.0),
        density: Some(8.69),
        group_block: "Transition metal",
        year_discovered: Some(1817),
    },
    Element {
        atomic_number: 49,
        symbol: "In",
        name: "Indium",
        atomic_mass: 114.818,
        cpk_hex_color: Some("A67573"),
        electron_configuration: "[Kr]5s2 4d10 5p1",
        electronegativity: Some(1.78),
        atomic_radius: Some(193.0),
        ionization_energy: Some(5.786),
        electron_affinity: Some(0.3),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(429.75),
        boiling_point: Some(2345.0),
        density: Some(7.31),
        group_block: "Post-transition metal",
        year_discovered: Some(1863),
    },
    Element {
        atomic_number: 50,
        symbol: "Sn",
        name: "Tin",
        atomic_mass: 118.71,
        cpk_hex_color: Some("668080"),
        electron_configuration: "[Kr]5s2 4d10 5p2",
        electronegativity: Some(1.96),
        atomic_radius: Some(217.0),
        ionization_energy: Some(7.344),
        electron_affinity: Some(1.2),
        oxidation_states: &[4, 2],
        standard_state: "Solid",
        melting_point: Some(505.08),
        boiling_point: Some(2875.0),
        density: Some(7.287),
        group_block: "Post-transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 51,
        symbol: "Sb",
        name: "Antimony",
        atomic_mass: 121.760,
        cpk_hex_color: Some("9E63B5"),
        electron_configuration: "[Kr]5s2 4d10 5p3",
        electronegativity: Some(2.05),
        atomic_radius: Some(206.0),
        ionization_energy: Some(8.64),
        electron_affinity: Some(1.07),
        oxidation_states: &[5, 3, -3],
        standard_state: "Solid",
        melting_point: Some(903.78),
        boiling_point: Some(1860.0),
        density: Some(6.685),
        group_block: "Metalloid",
        year_discovered: None,
    },
    Element {
        atomic_number: 52,
        symbol: "Te",
        name: "Tellurium",
        atomic_mass: 127.6,
        cpk_hex_color: Some("D47A00"),
        electron_configuration: "[Kr]5s2 4d10 5p4",
        electronegativity: Some(2.1),
        atomic_radius: Some(206.0),
        ionization_energy: Some(9.010),
        electron_affinity: Some(1.971),
        oxidation_states: &[6, 4, -2],
        standard_state: "Solid",
        melting_point: Some(722.66),
        boiling_point: Some(1261.0),
        density: Some(6.232),
        group_block: "Metalloid",
        year_discovered: Some(1782),
    },
    Element {
        atomic_number: 53,
        symbol: "I",
        name: "Iodine",
        atomic_mass: 126.9045,
        cpk_hex_color: Some("940094"),
        electron_configuration: "[Kr]5s2 4d10 5p5",
        electronegativity: Some(2.66),
        atomic_radius: Some(198.0),
        ionization_energy: Some(10.451),
        electron_affinity: Some(3.059),
        oxidation_states: &[7, 5, 1, -1],
        standard_state: "Solid",
        melting_point: Some(386.85),
        boiling_point: Some(457.55),
        density: Some(4.93),
        group_block: "Halogen",
        year_discovered: Some(1811),
    },
    Element {
        atomic_number: 54,
        symbol: "Xe",
        name: "Xenon",
        atomic_mass: 131.29,
        cpk_hex_color: Some("429EB0"),
        electron_configuration: "[Kr]5s2 4d10 5p6",
        electronegativity: Some(2.6),
        atomic_radius: Some(216.0),
        ionization_energy: Some(12.130),
        electron_affinity: None,
        oxidation_states: &[0],
        standard_state: "Gas",
        melting_point: Some(161.36),
        boiling_point: Some(165.03),
        density: Some(0.005887),
        group_block: "Noble gas",
        year_discovered: Some(1898),
    },
    Element {
        atomic_number: 55,
        symbol: "Cs",
        name: "Cesium",
        atomic_mass: 132.9054520,
        cpk_hex_color: Some("57178F"),
        electron_configuration: "[Xe]6s1",
        electronegativity: Some(0.79),
        atomic_radius: Some(343.0),
        ionization_energy: Some(3.894),
        electron_affinity: Some(0.472),
        oxidation_states: &[1],
        standard_state: "Solid",
        melting_point: Some(301.59),
        boiling_point: Some(944.0),
        density: Some(1.93),
        group_block: "Alkali metal",
        year_discovered: Some(1860),
    },
    Element {
        atomic_number: 56,
        symbol: "Ba",
        name: "Barium",
        atomic_mass: 137.33,
        cpk_hex_color: Some("00C900"),
        electron_configuration: "[Xe]6s2",
        electronegativity: Some(0.89),
        atomic_radius: Some(268.0),
        ionization_energy: Some(5.212),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(1000.0),
        boiling_point: Some(2170.0),
        density: Some(3.62),
        group_block: "Alkaline earth metal",
        year_discovered: Some(1808),
    },
    Element {
        atomic_number: 57,
        symbol: "La",
        name: "Lanthanum",
        atomic_mass: 138.9055,
        cpk_hex_color: Some("70D4FF"),
        electron_configuration: "[Xe]6s2 5d1",
        electronegativity: Some(1.1),
        atomic_radius: Some(240.0),
        ionization_energy: Some(5.577),
        electron_affinity: Some(0.5),
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1191.0),
        boiling_point: Some(3737.0),
        density: Some(6.15),
        group_block: "Lanthanide",
        year_discovered: Some(1839),
    },
    Element {
        atomic_number: 58,
        symbol: "Ce",
        name: "Cerium",
        atomic_mass: 140.116,
        cpk_hex_color: Some("FFFFC7"),
        electron_configuration: "[Xe]6s2 4f1 5d1",
        electronegativity: Some(1.12),
        atomic_radius: Some(235.0),
        ionization_energy: Some(5.539),
        electron_affinity: Some(0.5),
        oxidation_states: &[4, 3],
        standard_state: "Solid",
        melting_point: Some(1071.0),
        boiling_point: Some(3697.0),
        density: Some(6.770),
        group_block: "Lanthanide",
        year_discovered: Some(1803),
    },
    Element {
        atomic_number: 59,
        symbol: "Pr",
        name: "Praseodymium",
        atomic_mass: 140.90766,
        cpk_hex_color: Some("D9FFC7"),
        electron_configuration: "[Xe]6s2 4f3",
        electronegativity: Some(1.13),
        atomic_radius: Some(239.0),
        ionization_energy: Some(5.464),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1204.0),
        boiling_point: Some(3793.0),
        density: Some(6.77),
        group_block: "Lanthanide",
        year_discovered: Some(1885),
    },
    Element {
        atomic_number: 60,
        symbol: "Nd",
        name: "Neodymium",
        atomic_mass: 144.24,
        cpk_hex_color: Some("C7FFC7"),
        electron_configuration: "[Xe]6s2 4f4",
        electronegativity: Some(1.14),
        atomic_radius: Some(229.0),
        ionization_energy: Some(5.525),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1294.0),
        boiling_point: Some(3347.0),
        density: Some(7.01),
        group_block: "Lanthanide",
        year_discovered: Some(1885),
    },
    Element {
        atomic_number: 61,
        symbol: "Pm",
        name: "Promethium",
        atomic_mass: 144.91276,
        cpk_hex_color: Some("A3FFC7"),
        electron_configuration: "[Xe]6s2 4f5",
        electronegativity: None,
        atomic_radius: Some(236.0),
        ionization_energy: Some(5.55),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1315.0),
        boiling_point: Some(3273.0),
        density: Some(7.26),
        group_block: "Lanthanide",
        year_discovered: Some(1945),
    },
    Element {
        atomic_number: 62,
        symbol: "Sm",
        name: "Samarium",
        atomic_mass: 150.4,
        cpk_hex_color: Some("8FFFC7"),
        electron_configuration: "[Xe]6s2 4f6",
        electronegativity: Some(1.17),
        atomic_radius: Some(229.0),
        ionization_energy: Some(5.644),
        electron_affinity: None,
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1347.0),
        boiling_point: Some(2067.0),
        density: Some(7.52),
        group_block: "Lanthanide",
        year_discovered: Some(1879),
    },
    Element {
        atomic_number: 63,
        symbol: "Eu",
        name: "Europium",
        atomic_mass: 151.964,
        cpk_hex_color: Some("61FFC7"),
        electron_configuration: "[Xe]6s2 4f7",
        electronegativity: None,
        atomic_radius: Some(233.0),
        ionization_energy: Some(5.670),
        electron_affinity: None,
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1095.0),
        boiling_point: Some(1802.0),
        density: Some(5.24),
        group_block: "Lanthanide",
        year_discovered: Some(1901),
    },
    Element {
        atomic_number: 64,
        symbol: "Gd",
        name: "Gadolinium",
        atomic_mass: 157.2,
        cpk_hex_color: Some("45FFC7"),
        electron_configuration: "[Xe]6s2 4f7 5d1",
        electronegativity: Some(1.2),
        atomic_radius: Some(237.0),
        ionization_energy: Some(6.150),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1586.0),
        boiling_point: Some(3546.0),
        density: Some(7.90),
        group_block: "Lanthanide",
        year_discovered: Some(1880),
    },
    Element {
        atomic_number: 65,
        symbol: "Tb",
        name: "Terbium",
        atomic_mass: 158.92535,
        cpk_hex_color: Some("30FFC7"),
        electron_configuration: "[Xe]6s2 4f9",
        electronegativity: None,
        atomic_radius: Some(221.0),
        ionization_energy: Some(5.864),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1629.0),
        boiling_point: Some(3503.0),
        density: Some(8.23),
        group_block: "Lanthanide",
        year_discovered: Some(1843),
    },
    Element {
        atomic_number: 66,
        symbol: "Dy",
        name: "Dysprosium",
        atomic_mass: 162.500,
        cpk_hex_color: Some("1FFFC7"),
        electron_configuration: "[Xe]6s2 4f10",
        electronegativity: Some(1.22),
        atomic_radius: Some(229.0),
        ionization_energy: Some(5.939),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1685.0),
        boiling_point: Some(2840.0),
        density: Some(8.55),
        group_block: "Lanthanide",
        year_discovered: Some(1886),
    },
    Element {
        atomic_number: 67,
        symbol: "Ho",
        name: "Holmium",
        atomic_mass: 164.93033,
        cpk_hex_color: Some("00FF9C"),
        electron_configuration: "[Xe]6s2 4f11",
        electronegativity: Some(1.23),
        atomic_radius: Some(216.0),
        ionization_energy: Some(6.022),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1747.0),
        boiling_point: Some(2973.0),
        density: Some(8.80),
        group_block: "Lanthanide",
        year_discovered: Some(1878),
    },
    Element {
        atomic_number: 68,
        symbol: "Er",
        name: "Erbium",
        atomic_mass: 167.26,
        cpk_hex_color: None,
        electron_configuration: "[Xe]6s2 4f12",
        electronegativity: Some(1.24),
        atomic_radius: Some(235.0),
        ionization_energy: Some(6.108),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1802.0),
        boiling_point: Some(3141.0),
        density: Some(9.07),
        group_block: "Lanthanide",
        year_discovered: Some(1843),
    },
    Element {
        atomic_number: 69,
        symbol: "Tm",
        name: "Thulium",
        atomic_mass: 168.93422,
        cpk_hex_color: Some("00D452"),
        electron_configuration: "[Xe]6s2 4f13",
        electronegativity: Some(1.25),
        atomic_radius: Some(227.0),
        ionization_energy: Some(6.184),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1818.0),
        boiling_point: Some(2223.0),
        density: Some(9.32),
        group_block: "Lanthanide",
        year_discovered: Some(1879),
    },
    Element {
        atomic_number: 70,
        symbol: "Yb",
        name: "Ytterbium",
        atomic_mass: 173.05,
        cpk_hex_color: Some("00BF38"),
        electron_configuration: "[Xe]6s2 4f14",
        electronegativity: None,
        atomic_radius: Some(242.0),
        ionization_energy: Some(6.254),
        electron_affinity: None,
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1092.0),
        boiling_point: Some(1469.0),
        density: Some(6.90),
        group_block: "Lanthanide",
        year_discovered: Some(1878),
    },
    Element {
        atomic_number: 71,
        symbol: "Lu",
        name: "Lutetium",
        atomic_mass: 174.9668,
        cpk_hex_color: Some("00AB24"),
        electron_configuration: "[Xe]6s2 4f14 5d1",
        electronegativity: Some(1.27),
        atomic_radius: Some(221.0),
        ionization_energy: Some(5.426),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1936.0),
        boiling_point: Some(3675.0),
        density: Some(9.84),
        group_block: "Lanthanide",
        year_discovered: Some(1907),
    },
    Element {
        atomic_number: 72,
        symbol: "Hf",
        name: "Hafnium",
        atomic_mass: 178.49,
        cpk_hex_color: Some("4DC2FF"),
        electron_configuration: "[Xe]6s2 4f14 5d2",
        electronegativity: Some(1.3),
        atomic_radius: Some(212.0),
        ionization_energy: Some(6.825),
        electron_affinity: None,
        oxidation_states: &[4],
        standard_state: "Solid",
        melting_point: Some(2506.0),
        boiling_point: Some(4876.0),
        density: Some(13.3),
        group_block: "Transition metal",
        year_discovered: Some(1923),
    },
    Element {
        atomic_number: 73,
        symbol: "Ta",
        name: "Tantalum",
        atomic_mass: 180.9479,
        cpk_hex_color: Some("4DA6FF"),
        electron_configuration: "[Xe]6s2 4f14 5d3",
        electronegativity: Some(1.5),
        atomic_radius: Some(217.0),
        ionization_energy: Some(7.89),
        electron_affinity: Some(0.322),
        oxidation_states: &[5],
        standard_state: "Solid",
        melting_point: Some(3290.0),
        boiling_point: Some(5731.0),
        density: Some(16.4),
        group_block: "Transition metal",
        year_discovered: Some(1802),
    },
    Element {
        atomic_number: 74,
        symbol: "W",
        name: "Tungsten",
        atomic_mass: 183.84,
        cpk_hex_color: Some("2194D6"),
        electron_configuration: "[Xe]6s2 4f14 5d4",
        electronegativity: Some(2.36),
        atomic_radius: Some(210.0),
        ionization_energy: Some(7.98),
        electron_affinity: Some(0.815),
        oxidation_states: &[6],
        standard_state: "Solid",
        melting_point: Some(3695.0),
        boiling_point: Some(5828.0),
        density: Some(19.3),
        group_block: "Transition metal",
        year_discovered: Some(1783),
    },
    Element {
        atomic_number: 75,
        symbol: "Re",
        name: "Rhenium",
        atomic_mass: 186.207,
        cpk_hex_color: Some("267DAB"),
        electron_configuration: "[Xe]6s2 4f14 5d5",
        electronegativity: Some(1.9),
        atomic_radius: Some(217.0),
        ionization_energy: Some(7.88),
        electron_affinity: Some(0.15),
        oxidation_states: &[7, 6, 4],
        standard_state: "Solid",
        melting_point: Some(3459.0),
        boiling_point: Some(5869.0),
        density: Some(20.8),
        group_block: "Transition metal",
        year_discovered: Some(1925),
    },
    Element {
        atomic_number: 76,
        symbol: "Os",
        name: "Osmium",
        atomic_mass: 190.2,
        cpk_hex_color: Some("266696"),
        electron_configuration: "[Xe]6s2 4f14 5d6",
        electronegativity: Some(2.2),
        atomic_radius: Some(216.0),
        ionization_energy: Some(8.7),
        electron_affinity: Some(1.1),
        oxidation_states: &[4, 3],
        standard_state: "Solid",
        melting_point: Some(3306.0),
        boiling_point: Some(5285.0),
        density: Some(22.57),
        group_block: "Transition metal",
        year_discovered: Some(1803),
    },
    Element {
        atomic_number: 77,
        symbol: "Ir",
        name: "Iridium",
        atomic_mass: 192.22,
        cpk_hex_color: Some("175487"),
        electron_configuration: "[Xe]6s2 4f14 5d7",
        electronegativity: Some(2.2),
        atomic_radius: Some(202.0),
        ionization_energy: Some(9.1),
        electron_affinity: Some(1.565),
        oxidation_states: &[4, 3],
        standard_state: "Solid",
        melting_point: Some(2719.0),
        boiling_point: Some(4701.0),
        density: Some(22.42),
        group_block: "Transition metal",
        year_discovered: Some(1803),
    },
    Element {
        atomic_number: 78,
        symbol: "Pt",
        name: "Platinum",
        atomic_mass: 195.08,
        cpk_hex_color: Some("D0D0E0"),
        electron_configuration: "[Xe]6s1 4f14 5d9",
        electronegativity: Some(2.28),
        atomic_radius: Some(209.0),
        ionization_energy: Some(9.0),
        electron_affinity: Some(2.128),
        oxidation_states: &[4, 2],
        standard_state: "Solid",
        melting_point: Some(2041.55),
        boiling_point: Some(4098.0),
        density: Some(21.46),
        group_block: "Transition metal",
        year_discovered: Some(1735),
    },
    Element {
        atomic_number: 79,
        symbol: "Au",
        name: "Gold",
        atomic_mass: 196.96657,
        cpk_hex_color: Some("FFD123"),
        electron_configuration: "[Xe]6s1 4f14 5d10",
        electronegativity: Some(2.54),
        atomic_radius: Some(166.0),
        ionization_energy: Some(9.226),
        electron_affinity: Some(2.309),
        oxidation_states: &[3, 1],
        standard_state: "Solid",
        melting_point: Some(1337.33),
        boiling_point: Some(3129.0),
        density: Some(19.282),
        group_block: "Transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 80,
        symbol: "Hg",
        name: "Mercury",
        atomic_mass: 200.59,
        cpk_hex_color: Some("B8B8D0"),
        electron_configuration: "[Xe]6s2 4f14 5d10",
        electronegativity: Some(2.0),
        atomic_radius: Some(209.0),
        ionization_energy: Some(10.438),
        electron_affinity: None,
        oxidation_states: &[2, 1],
        standard_state: "Liquid",
        melting_point: Some(234.32),
        boiling_point: Some(629.88),
        density: Some(13.5336),
        group_block: "Transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 81,
        symbol: "Tl",
        name: "Thallium",
        atomic_mass: 204.383,
        cpk_hex_color: Some("A6544D"),
        electron_configuration: "[Xe]6s2 4f14 5d10 6p1",
        electronegativity: Some(1.62),
        atomic_radius: Some(196.0),
        ionization_energy: Some(6.108),
        electron_affinity: Some(0.2),
        oxidation_states: &[3, 1],
        standard_state: "Solid",
        melting_point: Some(577.0),
        boiling_point: Some(1746.0),
        density: Some(11.8),
        group_block: "Post-transition metal",
        year_discovered: Some(1861),
    },
    Element {
        atomic_number: 82,
        symbol: "Pb",
        name: "Lead",
        atomic_mass: 207.0,
        cpk_hex_color: Some("575961"),
        electron_configuration: "[Xe]6s2 4f14 5d10 6p2",
        electronegativity: Some(2.33),
        atomic_radius: Some(202.0),
        ionization_energy: Some(7.417),
        electron_affinity: Some(0.36),
        oxidation_states: &[4, 2],
        standard_state: "Solid",
        melting_point: Some(600.61),
        boiling_point: Some(2022.0),
        density: Some(11.342),
        group_block: "Post-transition metal",
        year_discovered: None,
    },
    Element {
        atomic_number: 83,
        symbol: "Bi",
        name: "Bismuth",
        atomic_mass: 208.98040,
        cpk_hex_color: Some("9E4FB5"),
        electron_configuration: "[Xe]6s2 4f14 5d10 6p3",
        electronegativity: Some(2.02),
        atomic_radius: Some(207.0),
        ionization_energy: Some(7.289),
        electron_affinity: Some(0.946),
        oxidation_states: &[5, 3],
        standard_state: "Solid",
        melting_point: Some(544.55),
        boiling_point: Some(1837.0),
        density: Some(9.807),
        group_block: "Post-transition metal",
        year_discovered: Some(1753),
    },
    Element {
        atomic_number: 84,
        symbol: "Po",
        name: "Polonium",
        atomic_mass: 208.98243,
        cpk_hex_color: Some("AB5C00"),
        electron_configuration: "[Xe]6s2 4f14 5d10 6p4",
        electronegativity: Some(2.0),
        atomic_radius: Some(197.0),
        ionization_energy: Some(8.417),
        electron_affinity: Some(1.9),
        oxidation_states: &[4, 2],
        standard_state: "Solid",
        melting_point: Some(527.0),
        boiling_point: Some(1235.0),
        density: Some(9.32),
        group_block: "Metalloid",
        year_discovered: Some(1898),
    },
    Element {
        atomic_number: 85,
        symbol: "At",
        name: "Astatine",
        atomic_mass: 209.98715,
        cpk_hex_color: Some("754F45"),
        electron_configuration: "[Xe]6s2 4f14 5d10 6p5",
        electronegativity: Some(2.2),
        atomic_radius: Some(202.0),
        ionization_energy: Some(9.5),
        electron_affinity: Some(2.8),
        oxidation_states: &[7, 5, 3, 1, -1],
        standard_state: "Solid",
        melting_point: Some(575.0),
        boiling_point: None,
        density: Some(7.0),
        group_block: "Halogen",
        year_discovered: Some(1940),
    },
    Element {
        atomic_number: 86,
        symbol: "Rn",
        name: "Radon",
        atomic_mass: 222.01758,
        cpk_hex_color: Some("428296"),
        electron_configuration: "[Xe]6s2 4f14 5d10 6p6",
        electronegativity: None,
        atomic_radius: Some(220.0),
        ionization_energy: Some(10.745),
        electron_affinity: None,
        oxidation_states: &[0],
        standard_state: "Gas",
        melting_point: Some(202.0),
        boiling_point: Some(211.45),
        density: Some(0.00973),
        group_block: "Noble gas",
        year_discovered: Some(1900),
    },
    Element {
        atomic_number: 87,
        symbol: "Fr",
        name: "Francium",
        atomic_mass: 223.01973,
        cpk_hex_color: Some("420066"),
        electron_configuration: "[Rn]7s1",
        electronegativity: Some(0.7),
        atomic_radius: Some(348.0),
        ionization_energy: Some(3.9),
        electron_affinity: Some(0.47),
        oxidation_states: &[1],
        standard_state: "Solid",
        melting_point: Some(300.0),
        boiling_point: None,
        density: None,
        group_block: "Alkali metal",
        year_discovered: Some(1939),
    },
    Element {
        atomic_number: 88,
        symbol: "Ra",
        name: "Radium",
        atomic_mass: 226.02541,
        cpk_hex_color: Some("007D00"),
        electron_configuration: "[Rn]7s2",
        electronegativity: Some(0.9),
        atomic_radius: Some(283.0),
        ionization_energy: Some(5.279),
        electron_affinity: None,
        oxidation_states: &[2],
        standard_state: "Solid",
        melting_point: Some(973.0),
        boiling_point: Some(1413.0),
        density: Some(5.0),
        group_block: "Alkaline earth metal",
        year_discovered: Some(1898),
    },
    Element {
        atomic_number: 89,
        symbol: "Ac",
        name: "Actinium",
        atomic_mass: 227.02775,
        cpk_hex_color: Some("70ABFA"),
        electron_configuration: "[Rn]7s2 6d1",
        electronegativity: Some(1.1),
        atomic_radius: Some(260.0),
        ionization_energy: Some(5.17),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1324.0),
        boiling_point: Some(3471.0),
        density: Some(10.07),
        group_block: "Actinide",
        year_discovered: Some(1899),
    },
    Element {
        atomic_number: 90,
        symbol: "Th",
        name: "Thorium",
        atomic_mass: 232.038,
        cpk_hex_color: Some("00BAFF"),
        electron_configuration: "[Rn]7s2 6d2",
        electronegativity: Some(1.3),
        atomic_radius: Some(237.0),
        ionization_energy: Some(6.08),
        electron_affinity: None,
        oxidation_states: &[4],
        standard_state: "Solid",
        melting_point: Some(2023.0),
        boiling_point: Some(5061.0),
        density: Some(11.72),
        group_block: "Actinide",
        year_discovered: Some(1828),
    },
    Element {
        atomic_number: 91,
        symbol: "Pa",
        name: "Protactinium",
        atomic_mass: 231.03588,
        cpk_hex_color: Some("00A1FF"),
        electron_configuration: "[Rn]7s2 5f2 6d1",
        electronegativity: Some(1.5),
        atomic_radius: Some(243.0),
        ionization_energy: Some(5.89),
        electron_affinity: None,
        oxidation_states: &[5, 4],
        standard_state: "Solid",
        melting_point: Some(1845.0),
        boiling_point: None,
        density: Some(15.37),
        group_block: "Actinide",
        year_discovered: Some(1913),
    },
    Element {
        atomic_number: 92,
        symbol: "U",
        name: "Uranium",
        atomic_mass: 238.0289,
        cpk_hex_color: Some("008FFF"),
        electron_configuration: "[Rn]7s2 5f3 6d1",
        electronegativity: Some(1.38),
        atomic_radius: Some(240.0),
        ionization_energy: Some(6.194),
        electron_affinity: None,
        oxidation_states: &[6, 5, 4, 3],
        standard_state: "Solid",
        melting_point: Some(1408.0),
        boiling_point: Some(4404.0),
        density: Some(18.95),
        group_block: "Actinide",
        year_discovered: Some(1789),
    },
    Element {
        atomic_number: 93,
        symbol: "Np",
        name: "Neptunium",
        atomic_mass: 237.048172,
        cpk_hex_color: Some("0080FF"),
        electron_configuration: "[Rn]7s2 5f4 6d1",
        electronegativity: Some(1.36),
        atomic_radius: Some(221.0),
        ionization_energy: Some(6.266),
        electron_affinity: None,
        oxidation_states: &[6, 5, 4, 3],
        standard_state: "Solid",
        melting_point: Some(917.0),
        boiling_point: Some(4175.0),
        density: Some(20.25),
        group_block: "Actinide",
        year_discovered: Some(1940),
    },
    Element {
        atomic_number: 94,
        symbol: "Pu",
        name: "Plutonium",
        atomic_mass: 244.06420,
        cpk_hex_color: Some("006BFF"),
        electron_configuration: "[Rn]7s2 5f6",
        electronegativity: Some(1.28),
        atomic_radius: Some(243.0),
        ionization_energy: Some(6.06),
        electron_affinity: None,
        oxidation_states: &[6, 5, 4, 3],
        standard_state: "Solid",
        melting_point: Some(913.0),
        boiling_point: Some(3501.0),
        density: Some(19.84),
        group_block: "Actinide",
        year_discovered: Some(1940),
    },
    Element {
        atomic_number: 95,
        symbol: "Am",
        name: "Americium",
        atomic_mass: 243.061380,
        cpk_hex_color: Some("545CF2"),
        electron_configuration: "[Rn]7s2 5f7",
        electronegativity: Some(1.3),
        atomic_radius: Some(244.0),
        ionization_energy: Some(5.993),
        electron_affinity: None,
        oxidation_states: &[6, 5, 4, 3],
        standard_state: "Solid",
        melting_point: Some(1449.0),
        boiling_point: Some(2284.0),
        density: Some(13.69),
        group_block: "Actinide",
        year_discovered: Some(1944),
    },
    Element {
        atomic_number: 96,
        symbol: "Cm",
        name: "Curium",
        atomic_mass: 247.07035,
        cpk_hex_color: Some("785CE3"),
        electron_configuration: "[Rn]7s2 5f7 6d1",
        electronegativity: Some(1.3),
        atomic_radius: Some(245.0),
        ionization_energy: Some(6.02),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1618.0),
        boiling_point: Some(3400.0),
        density: Some(13.51),
        group_block: "Actinide",
        year_discovered: Some(1944),
    },
    Element {
        atomic_number: 97,
        symbol: "Bk",
        name: "Berkelium",
        atomic_mass: 247.07031,
        cpk_hex_color: Some("8A4FE3"),
        electron_configuration: "[Rn]7s2 5f9",
        electronegativity: Some(1.3),
        atomic_radius: Some(244.0),
        ionization_energy: Some(6.23),
        electron_affinity: None,
        oxidation_states: &[4, 3],
        standard_state: "Solid",
        melting_point: Some(1323.0),
        boiling_point: None,
        density: Some(14.0),
        group_block: "Actinide",
        year_discovered: Some(1949),
    },
    Element {
        atomic_number: 98,
        symbol: "Cf",
        name: "Californium",
        atomic_mass: 251.07959,
        cpk_hex_color: Some("A136D4"),
        electron_configuration: "[Rn]7s2 5f10",
        electronegativity: Some(1.3),
        atomic_radius: Some(245.0),
        ionization_energy: Some(6.30),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1173.0),
        boiling_point: None,
        density: None,
        group_block: "Actinide",
        year_discovered: Some(1950),
    },
    Element {
        atomic_number: 99,
        symbol: "Es",
        name: "Einsteinium",
        atomic_mass: 252.0830,
        cpk_hex_color: Some("B31FD4"),
        electron_configuration: "[Rn]7s2 5f11",
        electronegativity: Some(1.3),
        atomic_radius: Some(245.0),
        ionization_energy: Some(6.42),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1133.0),
        boiling_point: None,
        density: None,
        group_block: "Actinide",
        year_discovered: Some(1952),
    },
    Element {
        atomic_number: 100,
        symbol: "Fm",
        name: "Fermium",
        atomic_mass: 257.09511,
        cpk_hex_color: Some("B31FBA"),
        electron_configuration: "[Rn] 5f12 7s2",
        electronegativity: Some(1.3),
        atomic_radius: None,
        ionization_energy: Some(6.50),
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1800.0),
        boiling_point: None,
        density: None,
        group_block: "Actinide",
        year_discovered: Some(1952),
    },
    Element {
        atomic_number: 101,
        symbol: "Md",
        name: "Mendelevium",
        atomic_mass: 258.09843,
        cpk_hex_color: Some("B30DA6"),
        electron_configuration: "[Rn]7s2 5f13",
        electronegativity: Some(1.3),
        atomic_radius: None,
        ionization_energy: Some(6.58),
        electron_affinity: None,
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1100.0),
        boiling_point: None,
        density: None,
        group_block: "Actinide",
        year_discovered: Some(1955),
    },
    Element {
        atomic_number: 102,
        symbol: "No",
        name: "Nobelium",
        atomic_mass: 259.10100,
        cpk_hex_color: Some("BD0D87"),
        electron_configuration: "[Rn]7s2 5f14",
        electronegativity: Some(1.3),
        atomic_radius: None,
        ionization_energy: Some(6.65),
        electron_affinity: None,
        oxidation_states: &[3, 2],
        standard_state: "Solid",
        melting_point: Some(1100.0),
        boiling_point: None,
        density: None,
        group_block: "Actinide",
        year_discovered: Some(1957),
    },
    Element {
        atomic_number: 103,
        symbol: "Lr",
        name: "Lawrencium",
        atomic_mass: 266.120,
        cpk_hex_color: Some("C70066"),
        electron_configuration: "[Rn]7s2 5f14 6d1",
        electronegativity: Some(1.3),
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[3],
        standard_state: "Solid",
        melting_point: Some(1900.0),
        boiling_point: None,
        density: None,
        group_block: "Actinide",
        year_discovered: Some(1961),
    },
    Element {
        atomic_number: 104,
        symbol: "Rf",
        name: "Rutherfordium",
        atomic_mass: 267.122,
        cpk_hex_color: Some("CC0059"),
        electron_configuration: "[Rn]7s2 5f14 6d2",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[4],
        standard_state: "Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1964),
    },
    Element {
        atomic_number: 105,
        symbol: "Db",
        name: "Dubnium",
        atomic_mass: 268.126,
        cpk_hex_color: Some("D1004F"),
        electron_configuration: "[Rn]7s2 5f14 6d3",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[5, 4, 3],
        standard_state: "Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1967),
    },
    Element {
        atomic_number: 106,
        symbol: "Sg",
        name: "Seaborgium",
        atomic_mass: 269.128,
        cpk_hex_color: Some("D90045"),
        electron_configuration: "[Rn]7s2 5f14 6d4",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[6, 5, 4, 3, 0],
        standard_state: "Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1974),
    },
    Element {
        atomic_number: 107,
        symbol: "Bh",
        name: "Bohrium",
        atomic_mass: 270.133,
        cpk_hex_color: Some("E00038"),
        electron_configuration: "[Rn]7s2 5f14 6d5",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[7, 5, 4, 3],
        standard_state: "Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1976),
    },
    Element {
        atomic_number: 108,
        symbol: "Hs",
        name: "Hassium",
        atomic_mass: 269.1336,
        cpk_hex_color: Some("E6002E"),
        electron_configuration: "[Rn]7s2 5f14 6d6",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[8, 6, 5, 4, 3, 2],
        standard_state: "Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1984),
    },
    Element {
        atomic_number: 109,
        symbol: "Mt",
        name: "Meitnerium",
        atomic_mass: 277.154,
        cpk_hex_color: Some("EB0026"),
        electron_configuration: "[Rn]7s2 5f14 6d7 (calculated)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[9, 8, 6, 4, 3, 1],
        standard_state: "Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1982),
    },
    Element {
        atomic_number: 110,
        symbol: "Ds",
        name: "Darmstadtium",
        atomic_mass: 282.166,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 5f14 6d8 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[8, 6, 4, 2, 0],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1994),
    },
    Element {
        atomic_number: 111,
        symbol: "Rg",
        name: "Roentgenium",
        atomic_mass: 282.169,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 5f14 6d9 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[5, 3, 1, -1],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1994),
    },
    Element {
        atomic_number: 112,
        symbol: "Cn",
        name: "Copernicium",
        atomic_mass: 286.179,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 5f14 6d10 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[2, 1, 0],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Transition metal",
        year_discovered: Some(1996),
    },
    Element {
        atomic_number: 113,
        symbol: "Nh",
        name: "Nihonium",
        atomic_mass: 286.182,
        cpk_hex_color: None,
        electron_configuration: "[Rn]5f14 6d10 7s2 7p1 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Post-transition metal",
        year_discovered: Some(2004),
    },
    Element {
        atomic_number: 114,
        symbol: "Fl",
        name: "Flerovium",
        atomic_mass: 290.192,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 7p2 5f14 6d10 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[6, 4, 1, 0],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Post-transition metal",
        year_discovered: Some(1998),
    },
    Element {
        atomic_number: 115,
        symbol: "Mc",
        name: "Moscovium",
        atomic_mass: 290.196,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 7p3 5f14 6d10 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[3, 1],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Post-transition metal",
        year_discovered: Some(2003),
    },
    Element {
        atomic_number: 116,
        symbol: "Lv",
        name: "Livermorium",
        atomic_mass: 293.205,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 7p4 5f14 6d10 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[4, 2, -2],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Post-transition metal",
        year_discovered: Some(2000),
    },
    Element {
        atomic_number: 117,
        symbol: "Ts",
        name: "Tennessine",
        atomic_mass: 294.211,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 7p5 5f14 6d10 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[5, 3, 1, -1],
        standard_state: "Expected to be a Solid",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Halogen",
        year_discovered: Some(2010),
    },
    Element {
        atomic_number: 118,
        symbol: "Og",
        name: "Oganesson",
        atomic_mass: 295.216,
        cpk_hex_color: None,
        electron_configuration: "[Rn]7s2 7p6 5f14 6d10 (predicted)",
        electronegativity: None,
        atomic_radius: None,
        ionization_energy: None,
        electron_affinity: None,
        oxidation_states: &[6, 4, 2, 1, 0, -1],
        standard_state: "Expected to be a Gas",
        melting_point: None,
        boiling_point: None,
        density: None,
        group_block: "Noble gas",
        year_discovered: Some(2006),
    },
];
